// Browser-ready photo copies; original HEIC files are retained in assets/.
const vehiclePhotos = {"hero": "assets/HERO.png", "front": "assets/IMG_6022.jpg", "rear": "assets/IMG_6024.jpg", "interior": "assets/IMG_6037.jpg", "detail": "assets/IMG_6034.jpg", "photo6021": "assets/IMG_6021.jpg", "photo6023": "assets/IMG_6023.jpg", "photo6026": "assets/IMG_6026.jpg", "photo6027": "assets/IMG_6027.jpg", "photo6028": "assets/IMG_6028.jpg", "photo6029": "assets/IMG_6029.jpg", "photo6038": "assets/IMG_6038.jpg", "photo6039": "assets/IMG_6039.jpg", "photo6042": "assets/IMG_6042.jpg", "photo6043": "assets/IMG_6043.jpg", "studioFront": "assets/HERO.png", "studioDetail": "assets/hero2.png", "collage": "assets/B006499A-0278-4378-9148-B3F7FE52D49B.png", "meetFront": "assets/611d0df6-7416-482e-9594-c0774b826c6d.jpg", "garageFront": "assets/8F3A2BEE-EEF0-4D59-A003-1FC7517E5020.png"};
const whatsappNumber = '41782603899';
const message = 'Hallo! Ich interessiere mich für deinen Ford Focus ST MK3 für CHF 11’900.–. Ist das Fahrzeug noch verfügbar? Gerne würde ich mehr erfahren und eine Besichtigung vereinbaren.';
document.querySelectorAll('.whatsapp').forEach(link => {link.href = `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`; link.target='_blank';link.rel='noopener noreferrer';});
const gallery = [{"key": "front", "label": "Front / ¾-Ansicht"}, {"key": "rear", "label": "Heck / ¾-Ansicht"}, {"key": "interior", "label": "Innenraum"}, {"key": "detail", "label": "Ego-X Auspuffanlage"}, {"key": "photo6021", "label": "Frontansicht"}, {"key": "photo6023", "label": "Seitenansicht links"}, {"key": "photo6026", "label": "Heckansicht"}, {"key": "photo6027", "label": "Heck / rechte Seite"}, {"key": "photo6028", "label": "Seitenansicht rechts"}, {"key": "photo6029", "label": "Front / rechte Seite"}, {"key": "photo6038", "label": "ST Sportsitze"}, {"key": "photo6039", "label": "Cockpit"}, {"key": "photo6042", "label": "Mittelkonsole"}, {"key": "photo6043", "label": "Rücksitze"}, {"key": "studioFront", "label": "Front / Studioansicht"}, {"key": "studioDetail", "label": "Seite / Detailansicht"}, {"key": "collage", "label": "Fotocollage"}, {"key": "meetFront", "label": "Front / Fahrzeugtreffen"}, {"key": "garageFront", "label": "Front / Tiefgarage"}];
function insertPhoto(el,key){if(!vehiclePhotos[key])return;const img=document.createElement('img');img.src=vehiclePhotos[key];img.alt=key==='hero'?'Ford Focus ST MK3':gallery.find(p=>p.key===key)?.label||'Ford Focus ST';img.loading=key==='hero'?'eager':'lazy';img.addEventListener('load',()=>{el.querySelectorAll('.placeholder-number,.placeholder-mark').forEach(n=>n.hidden=true);if(key==='hero')document.querySelector('.photo-note').hidden=true;});el.prepend(img);}
document.querySelectorAll('[data-photo]').forEach(el=>insertPhoto(el,el.dataset.photo));
const facts=[['Marke / Modell','Ford Focus ST MK3'],['Jahrgang','2015'],['Kilometerstand','187’725 km'],['Getriebe','Handschaltung'],['Motor','2.0 EcoBoost'],['Treibstoff','Benzin'],['Leistung','ca. 250 PS Serie'],['Farbe','Weiss / schwarze Front'],['Antrieb','Frontantrieb'],['Unfallfrei','Ja'],['MFK','gegen Aufpreis möglich']];
const icons=['M3 7h10l2 3v4H1v-4z M4 14v2m8-2v2 M4 7l1-4h6l1 4','M3 3h10v12H3z M3 6h10 M5 1v4m6-4v4','M2 13a7 7 0 1 1 12 0 M8 9l3-4 M4 13h8','M4 2v12m8-12v7M4 8h8 M2 2h4m4 0h4M2 14h4','M3 5h9v8H3z M5 2h5M8 2v3M12 7h3v4h-3','M8 1C6 5 3 7 3 10a5 5 0 0 0 10 0c0-3-3-5-5-9z','M9 1L3 9h5l-1 6 6-9H8z','M8 1L2 10a6 6 0 0 0 12 0z','M3 3h10v10H3z M1 5h2m10 0h2M1 11h2m10 0h2 M8 3v10','M8 1l6 2v5c0 3-3 6-6 7-3-1-6-4-6-7V3z M5 8l2 2 4-4','M3 2h10v13H3z M5 6h6M5 9h6M5 12h4'];
document.querySelector('#spec-list').innerHTML=facts.map(([label,value],i)=>`<div class="spec-row"><dt><svg viewBox="0 0 16 17" aria-hidden="true"><path d="${icons[i]}"/></svg>${label}</dt><dd>${value}</dd></div>`).join('');
const dialog=document.querySelector('#lightbox');let active=0;
function renderGallery(){const item=gallery[active];const media=document.querySelector('#lightbox-media');media.replaceChildren();media.innerHTML=`<span class="placeholder-number">${String(active+1).padStart(2,'0')}</span><span class="photo-label">${item.label.toUpperCase()}${vehiclePhotos[item.key]?'':' — FOTO FOLGT'}</span>`;insertPhoto(media,item.key);document.querySelector('#caption').textContent=`${String(active+1).padStart(2,'0')} / ${String(gallery.length).padStart(2,'0')} — ${item.label}`;}
document.querySelectorAll('[data-index]').forEach(btn=>btn.addEventListener('click',()=>{active=Number(btn.dataset.index);renderGallery();dialog.showModal();document.body.style.overflow='hidden';}));
function move(delta){active=(active+delta+gallery.length)%gallery.length;renderGallery();}
document.querySelector('#previous').addEventListener('click',()=>move(-1));document.querySelector('#next').addEventListener('click',()=>move(1));document.querySelector('#close-gallery').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>document.body.style.overflow='');dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);});let touchStart=0;dialog.addEventListener('touchstart',e=>touchStart=e.changedTouches[0].clientX,{passive:true});dialog.addEventListener('touchend',e=>{const delta=e.changedTouches[0].clientX-touchStart;if(Math.abs(delta)>60)move(delta<0?1:-1);},{passive:true});
if('IntersectionObserver'in window){if(!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('motion');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}const sticky=document.querySelector('.mobile-contact');const visible=new Set();const ctaObserver=new IntersectionObserver(entries=>{entries.forEach(e=>e.isIntersecting?visible.add(e.target):visible.delete(e.target));sticky.classList.toggle('is-hidden',visible.size>0);});document.querySelectorAll('.hero .cta,.contact .cta').forEach(el=>ctaObserver.observe(el));}
